// This file contains placeholder data that you'll be replacing with real data in the Data Fetching chapter:
// https://nextjs.org/learn/dashboard-app/fetching-data
const users = [
  {
    id: '410544b2-4001-4271-9855-fec4b6a6442a',
    name: 'User',
    email: 'user@nextmail.com',
    password: '123456',
  },
];

const members = [
  {
    name: 'member1',
    type: 'execom',
    role: 'role1',
    image_url: '/members/lee-robinson.png',
    year: '2022',
  },
  {
    name: 'member2',
    type: 'regular',
    role: 'role2',
    image_url: '/members/lee-robinson.png',
    year: '2024',
  },
  {
    name: 'member3',
    type: 'execom',
    role: 'role3',
    image_url: '/members/lee-robinson.png',
    year: '2023',
  },
  {
    name: 'member4',
    type: 'regular',
    role: 'role4',
    image_url: '/members/lee-robinson.png',
    year: '2021',
  },
  {
    name: 'member5',
    type: 'execom',
    role: 'role5',
    image_url: '/members/lee-robinson.png',
    year: '2020',
  },
  {
    name: 'member6',
    type: 'regular',
    role: 'role6',
    image_url: '/members/lee-robinson.png',
    year: '2019',
  },
  {
    name: 'member7',
    type: 'execom',
    role: 'role7',
    image_url: '/members/lee-robinson.png',
    year: '2024',
  },
  {
    name: 'member8',
    type: 'regular',
    role: 'role8',
    image_url: '/members/lee-robinson.png',
    year: '2023',
  },
];

const events = [
  {
    name: 'event1',
    image_url: '/events/lee-robinson.png',
    status: 'hosted',
    date: '2022-11-06',
    fee: '0',
    mode: 'online',
    venue: 'zoom',
    description: 'description1',
    link: 'link1',
  },
  {
    name: 'event2',
    image_url: '/events/lee-robinson.png',
    status: 'hosted',
    date: '2022-11-06',
    fee: '0',
    mode: 'offline',
    venue: 'venue2',
    description: 'description2',
    link: 'link2',
  },
  {
    name: 'event3',
    image_url: '/events/lee-robinson.png',
    status: 'hosted',
    date: '2022-11-06',
    fee: '0',
    mode: 'online',
    venue: 'zoom',
    description: 'description3',
    link: 'link3',
  },
  {
    name: 'event4',
    image_url: '/events/lee-robinson.png',
    status: 'hosted',
    date: '2022-10-06',
    fee: '50',
    mode: 'offline',
    venue: 'venue4',
    description: 'description4',
    link: 'link4',
  },
  {
    name: 'event5',
    image_url: '/events/lee-robinson.png',
    status: 'hosted',
    date: '2022-10-06',
    fee: '0',
    mode: 'online',
    venue: 'zoom',
    description: 'description5',
    link: 'link5',
  },
  {
    name: 'event6',
    image_url: '/events/lee-robinson.png',
    status: 'hsoted',
    date: '2022-10-06',
    fee: '0',
    mode: 'offline',
    venue: 'zoom',
    description: 'description6',
    link: 'link6',
  },
  {
    name: 'event7',
    image_url: '/events/lee-robinson.png',
    status: 'hosted',
    date: '2022-09-06',
    fee: '0',
    mode: 'offline',
    venue: 'zoom',
    description: 'description7',
    link: 'link7',
  },
  {
    name: 'event8',
    image_url: '/events/lee-robinson.png',
    status: 'hosted',
    date: '2022-09-06',
    fee: '0',
    mode: 'offline',
    venue: 'zoom',
    description: 'description8',
    link: 'link8',
  },
  {
    name: 'event9',
    image_url: '/events/lee-robinson.png',
    status: 'hosted',
    date: '2022-09-06',
    fee: '0',
    mode: 'offline',
    venue: 'zoom',
    description: 'description9',
    link: 'link9',
  },
  {
    name: 'event10',
    image_url: '/events/lee-robinson.png',
    status: 'hosted',
    date: '2022-08-06',
    fee: '0',
    mode: 'online',
    venue: 'zoom',
    description: 'description10',
    link: 'link10',
  },
];

module.exports = {
  users,
  events,
  members,
};
